### PR TITLE
Allow loading of AWS credentials from env

### PR DESCRIPTION
**Pull request by tommoor**

### CODE REVIEW

**Comment by flrent** [comment]
thanks guys for this. Useful indeed.

**Comment by flrent** [comment]
I will publish it to npm soon.

**Comment by flrent** [comment]
Published 0.2.1.

**Comment by tommoor** [comment]
Thanks @flrent - I'll update our app to reflect, nice thing is you can use this module in conjunction with https://github.com/MathieuLoutre/grunt-aws-s3 now

**Pull request merged**
