### PR TITLE
Correct debug statement on SIGINT

### PR DESCRIPTION
**Pull request by ap4y**
Fixes annoying issue with `grunt ^0.4.0`.

### CODE REVIEW

**Comment by Caioflandau** [comment]
:+1: 
Please merge this :smiley:

**Comment by msdark** [comment]
Very ugly issue with a very simple fix. Please merge ASAP

**Comment by celestesaad** [comment]
Please merge!

**Comment by ap4y** [comment]
In the meantime you can do this in your `package.json`: `"grunt-cloudfront": "git+https://github.com/ap4y/grunt-cloudfront.git#fix_sigint"`

**Comment by flrent** [comment]
Apologies for the delay! Merged. I'll try to publish this to npm asap.

**Comment by Caioflandau** [comment]
Thanks @flrent!

**Pull request merged**
